markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Boris Gorelik
url: http://gorelik.net
description: Boris Gorelik private site
twitter: boris_gorelik
github: bgbg
gravatar_url: http://www.gravatar.com/avatar/22d41e5b6ff197cd7900c0514d1bd305
